#!/usr/bin/env bash
# Turned on Apache Server with this magic line
# get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.
service apache2 start
